INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('86', 'Hasl', 'HO');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8601', '北京', 'BeiJing');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8602', '天津', 'TianJin');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8603', '青岛', 'QingDao');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8604', '山东', 'ShanDong');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8605', '江苏', 'JiangSu');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8606', '辽宁', 'LiaoNing');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8607', '四川', 'SiChuan');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8608', '河南', 'HeNan');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8609', '大连', 'DaLian');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8610', '广东', 'GuangDong');
/
INSERT INTO E_BDS_HRM_ORG(CODE, NAME, ORGCODE)
  VALUES('8611', '河北', 'HeBei');
/
