CREATE OR REPLACE VIEW SX_FM02 AS
SELECT
MAX(DECODE(IOR.INDEX_CODE,'FM02001',IOR.INDEX_RESULT_Q2)) COL_01,
MAX(DECODE(IOR.INDEX_CODE,'FM02002',IOR.INDEX_RESULT_Q2)) COL_02,
MAX(DECODE(IOR.INDEX_CODE,'FM02003',IOR.INDEX_RESULT_Q2)) COL_03,
MAX(DECODE(IOR.INDEX_CODE,'FM02004',IOR.INDEX_RESULT_Q2)) COL_04,
MAX(DECODE(IOR.INDEX_CODE,'FM02005',IOR.INDEX_RESULT_Q2)) COL_05,
MAX(DECODE(IOR.INDEX_CODE,'FM02006',IOR.INDEX_RESULT_Q2)) COL_06,
MAX(DECODE(IOR.INDEX_CODE,'FM02007',IOR.INDEX_RESULT_Q2)) COL_07,
MAX(DECODE(IOR.INDEX_CODE,'FM02008',IOR.INDEX_RESULT_Q2)) COL_08,
MAX(DECODE(IOR.INDEX_CODE,'FM02009',IOR.INDEX_RESULT_Q2)) COL_09,
MAX(DECODE(IOR.INDEX_CODE,'FM02010',IOR.INDEX_RESULT_Q2)) COL_10,
MAX(DECODE(IOR.INDEX_CODE,'FM02011',IOR.INDEX_RESULT_Q2)) COL_11,
MAX(DECODE(IOR.INDEX_CODE,'FM02012',IOR.INDEX_RESULT_Q2)) COL_12,
MAX(DECODE(IOR.INDEX_CODE,'FM02013',IOR.INDEX_RESULT_Q2)) COL_13,
MAX(DECODE(IOR.INDEX_CODE,'FM02014',IOR.INDEX_RESULT_Q2)) COL_14,
MAX(DECODE(IOR.INDEX_CODE,'FM02015',IOR.INDEX_RESULT_Q2)) COL_15,
IOR.ORG_CODE STOCK_ID,
TO_XBRL_TASK_BATCH(IOR.TASK_BATCH) REPORT_MARK_DATE
FROM T_IRR_ORG_RESULT IOR
INNER JOIN T_IRR_INDEX_INFO II ON IOR.INDEX_ID=II.ID
INNER JOIN T_IRR_PROJ_TYPE PT ON II.PROJ_TYPE_ID=PT.ID
WHERE PT.TYPE_CODE='FM02'
GROUP BY IOR.ORG_CODE,TO_XBRL_TASK_BATCH(IOR.TASK_BATCH);
