CREATE OR REPLACE VIEW SX_ZGS_OR18 AS
SELECT
MAX(DECODE(IOR.INDEX_CODE,'OR18001',IOR.INDEX_RESULT_Q2)) COL_1,
MAX(DECODE(IOR.INDEX_CODE,'OR18002',IOR.INDEX_RESULT_Q2)) COL_2,
MAX(DECODE(IOR.INDEX_CODE,'OR18003',IOR.INDEX_RESULT_Q2)) COL_3,
MAX(DECODE(IOR.INDEX_CODE,'OR18004',IOR.INDEX_RESULT_Q2)) COL_4,
MAX(DECODE(IOR.INDEX_CODE,'OR18005',IOR.INDEX_RESULT_Q2)) COL_5,
MAX(DECODE(IOR.INDEX_CODE,'OR18006',IOR.INDEX_RESULT_Q2)) COL_6,
IOR.ORG_CODE STOCK_ID,
TO_XBRL_TASK_BATCH(IOR.TASK_BATCH) REPORT_MARK_DATE
FROM T_IRR_ORG_RESULT IOR
INNER JOIN T_IRR_INDEX_INFO II ON IOR.INDEX_ID=II.ID
INNER JOIN T_IRR_PROJ_TYPE PT ON II.PROJ_TYPE_ID=PT.ID
WHERE PT.TYPE_CODE='OR18'
GROUP BY IOR.ORG_CODE,TO_XBRL_TASK_BATCH(IOR.TASK_BATCH);
