SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS WSP_AUTH_USER_ROLE;
DROP TABLE IF EXISTS WSP_AUTH_ROLE;
DROP TABLE IF EXISTS WSP_AUTH_USER;




/* Create Tables */

CREATE TABLE WSP_AUTH_ROLE
(
	FD_ID varchar(36) NOT NULL,
	FD_NAME varchar(255),
	-- 1：可用，0：不可用
	FD_ENABLE int COMMENT '1：可用，0：不可用',
	FD_DESCRIPTION varchar(255),
	PRIMARY KEY (FD_ID)
);


CREATE TABLE WSP_AUTH_USER
(
	FD_ID varchar(36) NOT NULL,
	FD_LOGINNAME varchar(255),
	FD_USERNAME varchar(255),
	FD_PASSWORD varchar(255),
	-- 1：可用，0：不可用
	FD_ENABLE int COMMENT '1：可用，0：不可用',
	FD_DESCRIPTION varchar(255),
	PRIMARY KEY (FD_ID)
);


CREATE TABLE WSP_AUTH_USER_ROLE
(
	FD_USER_ID varchar(36) NOT NULL,
	FD_ROLE_ID varchar(36) NOT NULL
);



/* Create Foreign Keys */

ALTER TABLE WSP_AUTH_USER_ROLE
	ADD FOREIGN KEY (FD_ROLE_ID)
	REFERENCES WSP_AUTH_ROLE (FD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WSP_AUTH_USER_ROLE
	ADD FOREIGN KEY (FD_USER_ID)
	REFERENCES WSP_AUTH_USER (FD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



